### ISSUE TITLE
Doesn't work properly with wrap setting

### ISSUE THREAD

**Issue by MasouShizuka** [Aasim-A/scrollEOF.nvim#3]
If there are lines wrapped, the scrolloff of end of the file will not be equal to the scrolloff in the settings, in some cases there is even no scrolloff.

For example (`scrolloff = 5`):
![1](https://github.com/Aasim-A/scrollEOF.nvim/assets/44764707/2b269dac-70e4-4629-b754-b344b14cef2a)
![2](https://github.com/Aasim-A/scrollEOF.nvim/assets/44764707/a0c0f6f7-9638-411b-ac44-338cd3bcc313)
![3](https://github.com/Aasim-A/scrollEOF.nvim/assets/44764707/12c53f96-4d3e-4700-84fe-bbbf729f1f70)

**Comment by Aasim-A** [comment]
I've looked into this for a while and haven't found a good solution.
Vim doesn't provide a good way to get the cursor position relative to the window instead of the line number.
I'll see if I can come up with a solution that fixes this as well as when you have code folded because that causes a similar issue.

**Comment by stevenxxiu** [comment]
I'm having the same issue with *Markdown* files. I don't hard wrap lines.

I wonder if https://github.com/neovim/neovim/issues/15754 could be of help?

`vim.fn.screenrow()` and `vim.fn.screencol()` appear to return the cursor position relative to the screen, instead of the line number.

**Comment by Aasim-A** [comment]
Hi @stevenxxiu , thanks for the suggestion. I'll see if I can make that work.
